arm-none-eabi-gcc -mcpu=cortex-m4 -mlittle-endian -mthumb -DSTM32F401xE -T ~/STM32Cube/Projects/STM32F401RE-Nucleo/Templates/TrueSTUDIO/STM32F4xx-Nucleo/STM32F401CE_FLASH.ld -Wl,--gc-sections system.o main.o startup_stm32f401xe.o -o main.elf




arm-none-eabi-gcc -Wall -mcpu=cortex-m4 -mlittle-endian -mthumb -I ~/STM32Cube/Drivers/CMSIS/Device/ST/STM32F4xx/Include -I ~/STM32Cube/Drivers/CMSIS/Include -DSTM32F401xE -Os -c system.c -o system.o
